config/routes.rb
Rails.application.routes.draw do
  root :to => 'lists#home'
  resources :lists do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks
  validates :name, :presence => true
  validates :image, :presence => true
  validates :description, :presence => true
  validates :githublink, :presence => true
  validates :livelink, :presence => true    
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list

  validates :description, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def home
    @lists = List.all
    render :home
  end

  def index
    @lists = List.all
    render :index
  end

  def show
    @list = List.find(params[:id])
    render :show
  end

  def new
    @list = List.new
    render :new
  end

  def create
  # list_params needed for list to appear. otherwise it will come up as blank
  # based on lessons (@list) can be added at the end of lists_path but still needs (list_params to work)
    @list = List.new(list_params)
    if @list.save
      flash[:notice] = "List successfully added~"
      redirect_to  lists_path
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
    render :edit
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    if @list.destroy
      flash[:notice] = "Item destroyed"
      redirect_to lists_path
    else
      render :new
    end
  end

  private
  def list_params
    params.require(:list).permit(:name, :image, :description, :githublink, :livelink)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @task = @list.tasks.new
  end

  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.new(task_params)
    if @task.save
      redirect_to list_path(@task.list)
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
    render :edit
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to lists_path
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to lists_path
  end

private
  def task_params
    params.require(:task).permit(:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= render "layouts/errors", :object =>@list %>

<%= form_for @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :image %>
  <%= f.text_field :image %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :githublink %>
  <%= f.text_field :githublink %>
  <%= f.label :livelink %>
  <%= f.text_field :livelink %>
  <%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<h1>Edit list</h1>

<%= render "lists/form" %>

app/views/lists/home.html.erb
<h1 id="portfolio">Portfolio</h1>
<div class="container">
<center>
  <ul>
    <% @lists.each do |list| %>
       <a href="<%=list_path(list)%>"><img class="img-fluid" src="<%= list.image %>" /></a>
    <% end %>
  </ul>
</center>
</div>

app/views/lists/index.html.erb
<h1>Forum</h1>
<div class="container">
  <ul>
    <% @lists.each do |list| %>
       <li><%= link_to list.name, list_path(list)%></li>
    <% end %>
  </ul>

  <%= link_to "ADD a post", new_list_path %>
</div>

app/views/lists/new.html.erb
<h1>New list</h1>

<!-- <a href="http://www.youtube.com">test</a> -->

<%= render "lists/form" %>

app/views/lists/show.html.erb
<% content_for(:title, "List | To Do") %>

<h1><%= @list.name %></h1>
<img src="<%= @list.image %>" />
<h3>Description: <%= @list.description %></h3>
<h3>Github link:<%= @list.githublink %></h3>
<h3>Live link:<%= @list.livelink %></h3>

<% if @list.tasks.any? %>
  <h4>Comments: </h4>
  <h1>
    <% @list.tasks.each do |task| %>
      <p>
        <%= task.description %> |
        <%= link_to "Edit", edit_list_task_path(@list, task) %> |
        <%= link_to "Delete", list_task_path(@list, task),
                                  :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
        </p>
    <% end %>
  </h1>
<% else %>
  <p>There are no comments yet!</p>
<% end %>

<p><%= link_to "Add a task", new_list_task_path(@list) %></p>
<p><%= link_to "Edit List", edit_list_url %></p>
<p><%= link_to "Delete List", list_path(@list),
                          :data => {:confirm => "You sure?",
                                    :method => "delete"} %></p>

<p><%= link_to "Return to lists", lists_path %></p>

app/views/tasks/_form.html.erb
<%= render('layouts/errors', :object => @task) %>

<%= form_for [@list, @task] do |f| %>
  <%= f.label :comments %>
  <%= f.text_field :description %>
  <p><%= f.submit %></p>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render "tasks/form" %>

app/views/tasks/new.html.erb
<h1>Adding A Comment<%= @list.name%></h1>

<%= render 'form' %>